%% Keep only strings with ones in "Presence" column
featuresOnes = struct('Presence', [], 'Area', [], ... 
                      'Eccentricity', [], 'EquivDiameter', [], ...
                      'MaxIntensity', [], 'MeanIntensity', [], ...
                      'MinIntensity', [], 'Variance', [], ...
                      'StandardDeviation' , [], 'Contrast', [], ...
                      'Correlation', [], 'Energy', [], ...
                      'Homogeneity', [], 'MajorAxisLength', [], ... 
                      'MinorAxisLength', [], 'Orientation', []);
temp = data;
numStrings = numel(temp);
for i = 1:numStrings
    if temp(i).Presence == 1
       featuresOnes = [temp(i), featuresOnes]; 
    end
end
featuresOnes(end) = [];
vars.keepOnes = {'i', 'temp'};
clear(vars.keepOnes{:});